name: reusable maven build
on:
  workflow_dispatch:


env:
  JOBLEVELSECRET: "some other value"
  JFROG_CLIENT_NAME: "jfrog"
  JFROG_SECRET: ${{ secrets.JFROG_CLIENT_SECRET }}

jobs: 
  build:
    name: POM build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: maven build
      run: mvn clean install